/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qurban;

import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeString.toLowerCase;


/**
 *
 * @author Aldi
 */
public class SIQJFrame extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form SIQJFrame
     */
    public SIQJFrame() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("images/logo.png"));
        this.setLocationRelativeTo(null);
        initComponents();
        config();
        tampilData();
        zakarLabel.setVisible(false);
        zakar.setVisible(false);
    }
    public static Connection con;
    public static Statement stat;
    public static ResultSet res;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ekor1 = new javax.swing.JCheckBox();
        kuponJDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        data1 = new javax.swing.JTable();
        judul = new javax.swing.JLabel();
        tukar = new javax.swing.JTabbedPane();
        dataPenerima = new javax.swing.JTable();
        inputHewan = new javax.swing.JPanel();
        jenis = new javax.swing.JTextField();
        jenisLabel = new javax.swing.JLabel();
        jantan = new javax.swing.JCheckBox();
        zakarLabel = new javax.swing.JLabel();
        zakar = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        usiaLabel = new javax.swing.JLabel();
        bobot = new javax.swing.JTextField();
        bobotLabel = new javax.swing.JLabel();
        kgLabel = new javax.swing.JLabel();
        sehat = new javax.swing.JCheckBox();
        buta = new javax.swing.JCheckBox();
        pincang = new javax.swing.JCheckBox();
        tanduk = new javax.swing.JCheckBox();
        telinga = new javax.swing.JCheckBox();
        ekor = new javax.swing.JCheckBox();
        pengurbanLabel = new javax.swing.JLabel();
        pengurban = new javax.swing.JTextField();
        bulanLabel = new javax.swing.JLabel();
        tambahButton = new javax.swing.JButton();
        textHasil = new java.awt.TextArea();
        jPanel2 = new javax.swing.JPanel();
        kuponField = new javax.swing.JTextField();
        nikLabel1 = new javax.swing.JLabel();
        tambahButton1 = new javax.swing.JButton();
        dataHewan = new javax.swing.JTable();
        inputPenerima = new javax.swing.JPanel();
        nikLabel = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        alamatLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        kerbau = new javax.swing.JCheckBox();
        kambing = new javax.swing.JCheckBox();
        sapi = new javax.swing.JCheckBox();
        domba = new javax.swing.JCheckBox();
        cetakButton = new javax.swing.JButton();
        hasilField = new javax.swing.JTextField();
        bar = new javax.swing.JProgressBar();

        ekor1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        ekor1.setText("Ekor Putus");
        ekor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ekor1MouseClicked(evt);
            }
        });
        ekor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kuponJDialogLayout = new javax.swing.GroupLayout(kuponJDialog.getContentPane());
        kuponJDialog.getContentPane().setLayout(kuponJDialogLayout);
        kuponJDialogLayout.setHorizontalGroup(
            kuponJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        kuponJDialogLayout.setVerticalGroup(
            kuponJDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        data1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        data1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data1MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judul.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("SISTEM INFORMASI QURBAN");

        tukar.setToolTipText("");
        tukar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tukar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tukarMouseClicked(evt);
            }
        });

        dataPenerima.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataPenerima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPenerimaMouseClicked(evt);
            }
        });
        tukar.addTab("Data Penerima Qurban", dataPenerima);

        jenis.setText("jenis hewan");
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });

        jenisLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jenisLabel.setText("Jenis");

        jantan.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jantan.setText("Jantan");
        jantan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jantanMouseClicked(evt);
            }
        });
        jantan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jantanActionPerformed(evt);
            }
        });

        zakarLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        zakarLabel.setText("Jumlah Zakar");

        zakar.setText("0");
        zakar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zakarMouseClicked(evt);
            }
        });
        zakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zakarActionPerformed(evt);
            }
        });

        usia.setText("0");
        usia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usiaMouseClicked(evt);
            }
        });
        usia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usiaActionPerformed(evt);
            }
        });

        usiaLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        usiaLabel.setText("Usia");

        bobot.setText("0");
        bobot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bobotMouseClicked(evt);
            }
        });
        bobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bobotActionPerformed(evt);
            }
        });

        bobotLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        bobotLabel.setText("Bobot");

        kgLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        kgLabel.setText("Kg");

        sehat.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        sehat.setText("Sehat");
        sehat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sehatMouseClicked(evt);
            }
        });
        sehat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sehatActionPerformed(evt);
            }
        });

        buta.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        buta.setText("Buta");
        buta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butaMouseClicked(evt);
            }
        });
        buta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaActionPerformed(evt);
            }
        });

        pincang.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        pincang.setText("Pincang");
        pincang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pincangMouseClicked(evt);
            }
        });
        pincang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pincangActionPerformed(evt);
            }
        });

        tanduk.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        tanduk.setText("Tanduk Patah");
        tanduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tandukMouseClicked(evt);
            }
        });
        tanduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tandukActionPerformed(evt);
            }
        });

        telinga.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        telinga.setText("Telinga Robek");
        telinga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telingaMouseClicked(evt);
            }
        });
        telinga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telingaActionPerformed(evt);
            }
        });

        ekor.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        ekor.setText("Ekor Putus");
        ekor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ekorMouseClicked(evt);
            }
        });
        ekor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekorActionPerformed(evt);
            }
        });

        pengurbanLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pengurbanLabel.setText("Pengurban");

        pengurban.setText("nama pengurban");
        pengurban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengurbanActionPerformed(evt);
            }
        });

        bulanLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        bulanLabel.setText("bulan");

        tambahButton.setText("Tambah");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputHewanLayout = new javax.swing.GroupLayout(inputHewan);
        inputHewan.setLayout(inputHewanLayout);
        inputHewanLayout.setHorizontalGroup(
            inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputHewanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tambahButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jantan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inputHewanLayout.createSequentialGroup()
                        .addComponent(jenisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inputHewanLayout.createSequentialGroup()
                        .addComponent(zakarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zakar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inputHewanLayout.createSequentialGroup()
                        .addComponent(bobotLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bobot, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inputHewanLayout.createSequentialGroup()
                        .addComponent(usiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usia, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bulanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30)
                .addGroup(inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputHewanLayout.createSequentialGroup()
                        .addGroup(inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sehat)
                            .addComponent(buta)
                            .addComponent(pincang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanduk)
                            .addComponent(telinga)
                            .addComponent(ekor))
                        .addGap(76, 76, 76))
                    .addGroup(inputHewanLayout.createSequentialGroup()
                        .addGroup(inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textHasil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(inputHewanLayout.createSequentialGroup()
                                .addComponent(pengurbanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pengurban, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(48, Short.MAX_VALUE))))
        );
        inputHewanLayout.setVerticalGroup(
            inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputHewanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputHewanLayout.createSequentialGroup()
                        .addGroup(inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jenisLabel)
                            .addComponent(sehat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jantan)
                            .addComponent(buta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zakarLabel)
                            .addComponent(pincang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pengurban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(usia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usiaLabel)
                                .addComponent(bulanLabel))
                            .addComponent(pengurbanLabel)))
                    .addGroup(inputHewanLayout.createSequentialGroup()
                        .addComponent(tanduk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(telinga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ekor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputHewanLayout.createSequentialGroup()
                        .addGroup(inputHewanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bobotLabel)
                            .addComponent(bobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kgLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tambahButton))
                    .addComponent(textHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        tukar.addTab("Tambah Hewan Qurban", inputHewan);
        inputHewan.getAccessibleContext().setAccessibleName("");

        kuponField.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        kuponField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kuponField.setText("Kode Kupon!");
        kuponField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kuponFieldActionPerformed(evt);
            }
        });

        nikLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nikLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nikLabel1.setText("Masukkan kode kupon yang ingin di tukar!");

        tambahButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tambahButton1.setText("Tukar");
        tambahButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahButton1MouseClicked(evt);
            }
        });
        tambahButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kuponField, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(nikLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(nikLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kuponField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tambahButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        tukar.addTab("Tukar Kupon", jPanel2);

        dataHewan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataHewan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataHewanMouseClicked(evt);
            }
        });
        tukar.addTab("Data Hewan Qurban", dataHewan);

        nikLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nikLabel.setText("NIK");

        nik.setText("NIK penerima");
        nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikActionPerformed(evt);
            }
        });

        namaLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        namaLabel.setText("Nama");

        nama.setText("nama penerima");
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        alamatLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        alamatLabel.setText("Alamat");

        alamat.setColumns(20);
        alamat.setRows(5);
        alamat.setText("alamat penerima");
        jScrollPane1.setViewportView(alamat);

        kerbau.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        kerbau.setText("Kerbau");
        kerbau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kerbauMouseClicked(evt);
            }
        });
        kerbau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kerbauActionPerformed(evt);
            }
        });

        kambing.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        kambing.setText("Kambing");
        kambing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kambingMouseClicked(evt);
            }
        });
        kambing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kambingActionPerformed(evt);
            }
        });

        sapi.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        sapi.setText("Sapi");
        sapi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sapiMouseClicked(evt);
            }
        });
        sapi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapiActionPerformed(evt);
            }
        });

        domba.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        domba.setText("Domba");
        domba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dombaMouseClicked(evt);
            }
        });
        domba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dombaActionPerformed(evt);
            }
        });

        cetakButton.setText("Cetak");
        cetakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakButtonActionPerformed(evt);
            }
        });

        hasilField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPenerimaLayout = new javax.swing.GroupLayout(inputPenerima);
        inputPenerima.setLayout(inputPenerimaLayout);
        inputPenerimaLayout.setHorizontalGroup(
            inputPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPenerimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPenerimaLayout.createSequentialGroup()
                        .addComponent(nikLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nik))
                    .addGroup(inputPenerimaLayout.createSequentialGroup()
                        .addGroup(inputPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(alamatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(cetakButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inputPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputPenerimaLayout.createSequentialGroup()
                                .addGroup(inputPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hasilField)
                                    .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(inputPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kambing, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(domba)
                                    .addComponent(sapi)
                                    .addComponent(kerbau)))
                            .addComponent(nama, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))))
                .addContainerGap())
        );
        inputPenerimaLayout.setVerticalGroup(
            inputPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPenerimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nikLabel)
                    .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(inputPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPenerimaLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(kambing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(domba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sapi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(inputPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kerbau)
                            .addComponent(hasilField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(inputPenerimaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(inputPenerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputPenerimaLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(inputPenerimaLayout.createSequentialGroup()
                                .addComponent(alamatLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cetakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))))))
        );

        tukar.addTab("Cetak Kupon", inputPenerima);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tukar)
                    .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tukar, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
        );

        tukar.getAccessibleContext().setAccessibleName("Cetak Kupon");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisActionPerformed

    private void jantanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jantanActionPerformed
        if(jantan.isSelected()) {
            zakarLabel.setVisible(true);
            zakar.setVisible(true);
        } else {
            zakarLabel.setVisible(false);
            zakar.setVisible(false);
        }
    }//GEN-LAST:event_jantanActionPerformed

    private void zakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zakarActionPerformed

    }//GEN-LAST:event_zakarActionPerformed

    private void zakarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zakarMouseClicked
        if(!jantan.isSelected()) {
            zakarLabel.setVisible(false);
            zakar.setVisible(false);
        }
    }//GEN-LAST:event_zakarMouseClicked

    private void jantanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jantanMouseClicked
        if(!jantan.isSelected()) {
            zakarLabel.setVisible(false);
            zakar.setVisible(false);
        }
    }//GEN-LAST:event_jantanMouseClicked

    private void usiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usiaMouseClicked

    private void usiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usiaActionPerformed

    private void bobotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bobotMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bobotMouseClicked

    private void bobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bobotActionPerformed

    private void sehatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sehatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sehatMouseClicked

    private void sehatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sehatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sehatActionPerformed

    private void butaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_butaMouseClicked

    private void butaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butaActionPerformed

    private void pincangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pincangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pincangMouseClicked

    private void pincangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pincangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pincangActionPerformed

    private void tandukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tandukMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tandukMouseClicked

    private void tandukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tandukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tandukActionPerformed

    private void telingaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telingaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_telingaMouseClicked

    private void telingaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telingaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telingaActionPerformed

    private void ekorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ekorMouseClicked

    private void ekorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ekorActionPerformed

    private void pengurbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengurbanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pengurbanActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        String pengurbanValue = pengurban.getText(), jenisValue = jenis.getText(), zakarValue = zakar.getText(), umurValue = usia.getText(), bobotValue = bobot.getText(), count=getCountHewan();
        int zakarIntValue = Integer.parseInt(zakarValue), umurIntValue = Integer.parseInt(umurValue), bobotIntValue = Integer.parseInt(bobotValue);
        boolean sehatValue, butaValue, pincangValue, tandukValue, telingaValue, ekorValue, jantanValue;
        pengurbanValue=pengurbanValue.toLowerCase();
        jenisValue=jenisValue.toLowerCase();
        sehatValue = getCondition(sehat);
        butaValue = getCondition(buta);
        pincangValue = getCondition(pincang);
        tandukValue = getCondition(tanduk);
        telingaValue = getCondition(telinga);
        ekorValue = getCondition(ekor);
        jantanValue = getCondition(jantan);
        switch(jenisValue){
            case "kambing" : 
                Kambing kambing = new Kambing(jantanValue, zakarIntValue, umurIntValue, bobotIntValue, sehatValue, butaValue, pincangValue, tandukValue, telingaValue, ekorValue, pengurbanValue, count);
                tambahHewan(kambing);
                break;
            case "domba" : 
                Domba domba = new Domba(jantanValue, zakarIntValue, umurIntValue, bobotIntValue, sehatValue, butaValue, pincangValue, tandukValue, telingaValue, ekorValue, pengurbanValue, count);
                tambahHewan(domba);
                break;
            case "sapi" : 
                Sapi sapi = new Sapi(jantanValue, zakarIntValue, umurIntValue, bobotIntValue, sehatValue, butaValue, pincangValue, tandukValue, telingaValue, ekorValue, pengurbanValue, count);
                tambahHewan(sapi);
                break;
            case "kerbau" : 
                Kerbau kerbau = new Kerbau(jantanValue, zakarIntValue, umurIntValue, bobotIntValue, sehatValue, butaValue, pincangValue, tandukValue, telingaValue, ekorValue, pengurbanValue, count);
                tambahHewan(kerbau);
                break;
        }
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void nikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void ekor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekor1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ekor1MouseClicked

    private void ekor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ekor1ActionPerformed

    private void kerbauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kerbauMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kerbauMouseClicked

    private void kerbauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kerbauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kerbauActionPerformed

    private void kambingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kambingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kambingMouseClicked

    private void kambingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kambingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kambingActionPerformed

    private void sapiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sapiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sapiMouseClicked

    private void sapiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sapiActionPerformed

    private void dombaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dombaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dombaMouseClicked

    private void dombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dombaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dombaActionPerformed

    private void cetakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakButtonActionPerformed
        String nikValue = nik.getText(), namaValue = nama.getText(), alamatValue = alamat.getText(), cari = "";
        boolean kambingValue, dombaValue, sapiValue, kerbauValue;
        kambingValue = getCondition(kambing);
        dombaValue = getCondition(domba);
        sapiValue = getCondition(sapi);
        kerbauValue = getCondition(kerbau);
        cari+=getLikeCondition(cari,kambingValue,"Kambing");
        cari+=getLikeCondition(cari,dombaValue,"Domba");
        cari+=getLikeCondition(cari,sapiValue,"Sapi");
        cari+=getLikeCondition(cari,kerbauValue,"Kerbau");
        cetak(cetakKupon(cari, nikValue, namaValue, alamatValue));
        Runtime rt = Runtime.getRuntime();
        String path = "d:/kupon.txt";
        try {
            Process p = rt.exec("notepad "+path);
        } catch (IOException ex) {
            Logger.getLogger(SIQJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cetakButtonActionPerformed

    private void hasilFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilFieldActionPerformed

    private void dataPenerimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPenerimaMouseClicked
        tampilData();
    }//GEN-LAST:event_dataPenerimaMouseClicked

    private void tukarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tukarMouseClicked
        tampilData();
    }//GEN-LAST:event_tukarMouseClicked

    private void data1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_data1MouseClicked

    private void dataHewanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataHewanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dataHewanMouseClicked

    private void kuponFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kuponFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kuponFieldActionPerformed

    private void tambahButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahButton1ActionPerformed

    private void tambahButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahButton1MouseClicked
        String kuponValue = kuponField.getText();
        loading();
        tukarKupon(kuponValue);
    }//GEN-LAST:event_tambahButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    private void config(){
        try{
            String url = "jdbc:mysql://localhost/siqurban";
            String user = "root";
            String pass = "";
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url,user,pass);
            stat = con.createStatement();
        }catch(ClassNotFoundException | SQLException e){
            System.err.println("Koneksi gagal "+ e.getMessage());
        }
    }
    private void loading(){
        Thread th = new Thread(this);
        th.start();
    }
    private String getLikeCondition(String query, boolean kondisi, String hewan){
        String hasil="";
        if(kondisi){
            if("".equals(query)){
                hasil+=" AND ";
            }else{
                hasil+=" OR ";
            }
            hasil+="kode LIKE '"+hewan+"%'";
        }
        return hasil;
    }
    private boolean getCondition(javax.swing.JCheckBox field){
        if(field.isSelected()){
            return true;
        } else {
            return false;
        }
    }
    private void tampilData(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Nama");
        tabel.addColumn("Alamat");
        dataPenerima.setModel(tabel);
        try{
            res=stat.executeQuery("select nama, alamat from penerima");
            while (res.next()){
                tabel.addRow(new Object[]{
                    res.getString("nama"),
                    res.getString("alamat"),
                });
            }
        }catch(SQLException e){
            System.err.println("Tampilan gagal "+ e.getMessage());
        }
        DefaultTableModel tabel2 = new DefaultTableModel();
        tabel2.addColumn("Kode");
        tabel2.addColumn("Bobot");
        tabel2.addColumn("Sisa Kantong");
        dataHewan.setModel(tabel2);
        try{
            res=stat.executeQuery("select kode, bobot, kantong from hewan");
            while (res.next()){
                tabel2.addRow(new Object[]{
                    res.getString("kode"),
                    res.getString("bobot")+" kilogram",
                    res.getString("kantong")+" bungkus",
                });
            }
        }catch(SQLException e){
            System.err.println("Tampilan gagal "+ e.getMessage());
        }
    }
    public void cetak(String data){
        FileOutputStream foutput=null;
        //membuka file
        try{
            foutput = new FileOutputStream("d:/kupon.txt");
        }catch(IOException e){}
        //menulis data kedalam file
        try{
            for(int i=0;i<data.length();i++){
                foutput.write((int) data.charAt(i));
            }
        }catch(IOException e){}
        try{
            foutput.close();
        }catch(IOException e){}
    }
    private String cetakKupon(String like, String nik, String nama, String alamat){
        String kodeQurban="";
        String kodeKupon="";
        String kupon="";
        int sisaKantong=0;
        try{
            String sql = "SELECT * FROM hewan WHERE kantong>0"+like+" LIMIT 1";
//            System.out.println(sql);
            res=stat.executeQuery(sql);
            while (res.next()){
                kodeQurban = res.getString("kode");
                sisaKantong = res.getInt("kantong");
//                System.out.println(kodeQurban);
//                System.out.println(sisaKantong);
            }
        }catch(SQLException e){
            System.err.println("Tampilan gagal "+ e.getMessage());
        }
        if(kodeQurban==""){
            hasilField.setText("Daging tidak tersedia!");
        }else{
            hasilField.setText("Alhamdulillah! masih ada daging.");
            try{
                stat.executeUpdate("INSERT INTO penerima(no_kk, nama, alamat) VALUES ('"+nik+"', '"+nama+"', '"+alamat+"')");
            }catch(SQLException e){
                System.err.println("Tampilan gagal "+ e.getMessage());
            }
            kodeKupon+=kodeQurban+nik.charAt(0)+nik.charAt(7)+nik.charAt(15)+sisaKantong;
            try{
                stat.executeUpdate("INSERT INTO kupon(id, kode, no_kk) VALUES ('"+kodeKupon+"', '"+kodeQurban+"', '"+nik+"')");
            }catch(SQLException e){
                System.err.println("Tampilan gagal "+ e.getMessage());
            }
            try{
                stat.executeUpdate("UPDATE hewan SET kantong = '"+(sisaKantong-1)+"' WHERE kode = '"+kodeQurban+"'");
            }catch(SQLException e){
                System.err.println("Tampilan gagal "+ e.getMessage());
            }
            kupon+="| "+kodeKupon+" | "+nama+" | "+alamat+" |";
        }
        return kupon;
    }
    private String getCountHewan(){
        String CountHewan = "";
        try{
            String sql = "SELECT COUNT(*) AS hasil FROM hewan";
            res=stat.executeQuery(sql);
            while (res.next()){
                CountHewan = res.getString("hasil");
            }
        }catch(SQLException e){
            System.err.println("Tampilan gagal "+ e.getMessage());
        }
        return CountHewan;
    }
    private void tukarKupon(String kode){
        String kodeKupon="";
        String nik="";
        try{
            String sql = "SELECT id, no_kk FROM kupon WHERE id = '"+kode+"' LIMIT 1";
            res=stat.executeQuery(sql);
            while (res.next()){
                kodeKupon = res.getString("id");
                nik = res.getString("no_kk");
            }
        }catch(SQLException e){
            System.err.println("Tampilan gagal "+ e.getMessage());
        }
        if(kodeKupon==""){
            kuponField.setText("Kupon tidak ditemukan!");
        }else{
            try{
                stat.executeUpdate("DELETE FROM kupon WHERE id = '"+kodeKupon+"'");
            }catch(SQLException e){
                System.err.println("Tampilan gagal "+ e.getMessage());
            }
            try{
                stat.executeUpdate("DELETE FROM penerima WHERE no_kk = '"+nik+"'");
                kuponField.setText("Kupon berhasil ditukar!");
            }catch(SQLException e){
                System.err.println("Tampilan gagal "+ e.getMessage());
            }
        }
        
    }
    private void tambahHewan(Hewan qurban){
        textHasil.setText(qurban.cekStatus());
        if(qurban.status){
            try{
                stat.executeUpdate("INSERT INTO hewan(kode, bobot, jenis, kantong, Pengurban) VALUES ('"+qurban.kode+"', "+qurban.bobot+", '"+qurban.jenis+"', "+(qurban.bobot/3)+", '"+qurban.pengurban+"')");
            }catch(SQLException e){
                System.err.println("Tampilan gagal "+ e.getMessage());
            }
        }
    }
    private static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look  feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIQJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIQJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIQJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIQJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIQJFrame().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JProgressBar bar;
    private javax.swing.JTextField bobot;
    private javax.swing.JLabel bobotLabel;
    private javax.swing.JLabel bulanLabel;
    private javax.swing.JCheckBox buta;
    private javax.swing.JButton cetakButton;
    private javax.swing.JTable data1;
    private javax.swing.JTable dataHewan;
    private javax.swing.JTable dataPenerima;
    private javax.swing.JCheckBox domba;
    private javax.swing.JCheckBox ekor;
    private javax.swing.JCheckBox ekor1;
    private javax.swing.JTextField hasilField;
    private javax.swing.JPanel inputHewan;
    private javax.swing.JPanel inputPenerima;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jantan;
    private javax.swing.JTextField jenis;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JLabel judul;
    private javax.swing.JCheckBox kambing;
    private javax.swing.JCheckBox kerbau;
    private javax.swing.JLabel kgLabel;
    private javax.swing.JTextField kuponField;
    private javax.swing.JDialog kuponJDialog;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField nik;
    private javax.swing.JLabel nikLabel;
    private javax.swing.JLabel nikLabel1;
    private javax.swing.JTextField pengurban;
    private javax.swing.JLabel pengurbanLabel;
    private javax.swing.JCheckBox pincang;
    private javax.swing.JCheckBox sapi;
    private javax.swing.JCheckBox sehat;
    private javax.swing.JButton tambahButton;
    private javax.swing.JButton tambahButton1;
    private javax.swing.JCheckBox tanduk;
    private javax.swing.JCheckBox telinga;
    private java.awt.TextArea textHasil;
    private javax.swing.JTabbedPane tukar;
    private javax.swing.JTextField usia;
    private javax.swing.JLabel usiaLabel;
    private javax.swing.JTextField zakar;
    private javax.swing.JLabel zakarLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        //bar.setValue(50);
        //bar.repaint();
        try { 
            for (int i =0;i <= 100;i++) { 
                // fill the menu bar 
                bar.setValue(i); 
                // delay the thread 
                Thread.sleep(10);  
                System.out.println(bar.getValue());
            } 
        } 
        catch (Exception e) { 
        }  //To change body of generated methods, choose Tools | Templates.
    }
}
